apiVersion: v2
name: observability
version: 1.0.0
dependencies:
- name: kube-prometheus-stack
  version: 55.5.0
  repository: https://prometheus-community.github.io/helm-charts
- name: loki
  version: 5.41.4
  repository: https://grafana.github.io/helm-charts
- name: tempo 
  version: 1.7.1
  repository: https://grafana.github.io/helm-charts